project:
  type: website
  output-dir: docs

website:
  title: 'sboteros'
  description: 'Análisis de datos, programación y opinión'
  navbar:
    left:
      - href: index.qmd
        text: 'Sobre mí'
      - href: posts.qmd
        text: 'Ciencia de Datos'
      - href: opinion.qmd
        text: 'Opinión'
    right:
      - icon: rss
        href: sitemap.xml
      - icon: file-earmark-text-fill
        href: legal.qmd
        text: 'Información legal'
    logo: assets/img/logo_128.ico
    theme:
      light: flatly
      dark: darkly
  site-url: www.sboteros.com
  repo-url: https://github.com/sboteros/sboteros.github.io
  reader-mode: true
  search: true
  page-footer: '<a href="https://creativecommons.org">Página personal</a> © 2025 por <a href="https://creativecommons.org">Santiago Botero Sierra</a> está licenciada bajo <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.es">CC BY-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" style="max-width: 1em;max-height:1em;margin-left: .2em;">'
  page-navigation: true
  favicon: assets/img/logo_512.ico
  twitter-card: true
  open-graph:
    locale: es_ES
    site-name: sboteros

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
