---
title: 'Licencias'
---

El contenido original de esta página se encuenta bajo la licencia Creative Commons Atribución/Reconocimiento-CompartirIgual 4.0 Internacional, puede encontrar los detalles de la licencia [aquí](https://creativecommons.org/licenses/by-sa/4.0/deed.es). Un resumen se muestra en el siguiente recuadro.

:::{.callout-important}
Usted es libre de:

+ **Compartir** — copiar y redistribuir el material en cualquier medio o formato para cualquier propósito, incluso comercialmente.
+ **Adaptar** — remezclar, transformar y construir a partir del material para cualquier propósito, incluso comercialmente.

    La licenciante no puede revocar estas libertades en tanto usted siga los términos de la licencia

Bajo los siguientes términos:

+ **Atribución** — Usted debe dar *crédito de manera adecuada*, brindar un enlace a la licencia, e *indicar si se han realizado cambios*. Puede hacerlo en cualquier forma razonable, pero no de forma tal que sugiera que usted o su uso tienen el apoyo de la licenciante.
+ **CompartirIgual** — Si remezcla, transforma o crea a partir del material, debe distribuir su contribución bajo la la *misma licencia* del original.
+ **No hay restricciones adicionales** — No puede aplicar términos legales ni *medidas tecnológicas* que restrinjan legalmente a otras a hacer cualquier uso permitido por la licencia.

**Avisos:**

No tiene que cumplir con la licencia para elementos del material en el dominio público o cuando su uso esté permitido por una *excepción o limitación* aplicable.

No se dan garantías. La licencia podría no darle todos los permisos que necesita para el uso que tenga previsto. Por ejemplo, otros derechos como *publicidad, privacidad, o derechos morales* pueden limitar la forma en que utilice el material.
:::

En adición al contenido original, puede haber contenido generado por inteligencia artificial que no se encuentra referenciado completamente. Este contenido corresponde, de manera enunciativa mas no limitativa, al logo de la página, a las descripciones e imágenes de portada de entradas en el blog, a los textos que se utilicen para difusión en redes sociales, a traducciones de fragmentos de textos al español o a correcciones de estilo para textos en idiomas diferentes al español. Una parte de este material fue generada mediante el uso de Chat-GPT de Open-AI, sin que necesariamente se haga la mención específica en cada ocasión. Sin embargo, no se hará uso de inteligencia artificial para el fondo de ningún análisis u opinión presentada en esta página o, en su caso, se hará el descargo de responsabilidad correspondiente. Al respecto, el autor cuenta con los derechos para el uso de esta información, como se desprende de las [Condiciones de uso](https://openai.com/es-419/policies/terms-of-use/), consultadas el 23 de mayo de 2025, en donde se señala:

> **Propiedad del Contenido**. Entre usted y OpenAI, y en la medida en que lo permita la legislación aplicable, usted (a) conserva sus derechos de propiedad sobre la Información y (b) es el propietario de los Resultados. Por la presente, le cedemos todos nuestros derechos, títulos e intereses, si los hubiera, sobre los Resultados. 

Asimismo, las bases de datos, archivos electrónicos y otro material que se utilice para la generación de gráficas o información estadística puede contener licencias diversas. Siempre que las licencias lo permitan, esta información será compartida a través de un enlace en Dropbox y se harán las referencias a que haya lugar. La incorporación de esta información en este sitio no modifica ni sustituye a las licencias que el autor de estos materiales les haya asignado originalmente.

De forma similar, puede haber contenido con caracter de difusión de información, tal como cartas públicas, comunicados, pronunciamentos, entre otros, que no corresponden a autoría propia. En dichos casos se hará mención a la autoría de los documentos y estos no adquieren la licencia de este sitio, sino que conservan la licencia original que les fue asignada por los autores.

Los comentarios sobre las entradas a los blogs son responsabilidad exclusiva de sus autores, quienes conservan todos los derechos y obligaciones sobre los mismos. Estos se encuentran sujetos a las políticas de moderación y etiquetado propias de BluSky y/o las plataformas que los albergan y no reciben ninguna moderación por parte de este sitio, por lo que se recomienda discreción al momento de su análisis.