---
title: "Untitled"
format: html
---

```{julia}
using Dates, DataFrames, JSON, MarkdownTables, Random, StatsPlots
rng = Xoshiro(20250331)
```

# Introducción

@sadit_algoritmos[capítulo 5] discute algoritmos adaptables de búsqueda en arreglos organizados. En el modelo de comparación, estos algoritmos buscan identificar la posición de inserción, $p$, en la que debe acomodarse un valor $x$ para que el arreglo $A = (a_1, \dots, a_n), \, a_1 \leq \dots \leq a_n$ se mantenga ordenado después de la inserción de $x$.

En la @sec-busqueda se presentan e implementan en `Julia` los algoritmos analizados, tanto para el caso base (la búsqueda binaria), cuyo costo depende del tamaño del arreglo, como para los algoritmos adaptables. Como se observa en dicha sección, la particularidad de estos últimos es que su costo de ejecución depende de $p$ y no del tamaño del arreglo.

A continuación, en la @sec-experimentos se implementan diversos experimentos para probar cada algoritmo en cuanto al tiempo de ejecución y el número de operaciones de comparación requeridas. Al respecto, se observa que en los experimentos realizados no se satisface la expectativa de que el tiempo de ejecución y el número de operaciones de los algoritmos analizados dependen de $p$.

Por lo tanto, en la @sec-conclusion se concluye que se requiere mayor investigación para determinar la causa del comportamiento inesperado.

# Algoritmos de búsqueda {#sec-busqueda}

En esta sección se analizan diversos algoritmos de búsqueda descritos en @sadit_algoritmos[capítulo 5], así como una implementación propia de un algoritmo de búsqueda sobre SkipLists. Para cada uno, se explica cuál es el costo del problema y se describe una función en `Julia` para su implementación.

## Búsqueda binaria acotada {#sec-binaria}

La búsqueda binaria en el subarreglo $A[i:f]$ consiste en verificar si $x$ se encuentra antes o después del punto medio, $m = \lfloor \frac{i + f}{2} \rfloor$, para lo cual se debe comparar $x$ con $a_m$, actualizar $i$ o $f$ para continuar la búsqueda en un arreglo de la mitad del tamaño e iterar hasta llegar al caso base, en donde $i \geq f$. Cuando se llega a ese punto, entonces únicamente hay que comparar $x$ con el valor de $a_i$ correspondiente y seleccionar $p$ como $i$ o $i + 1$, dependiendo del resultado obtenido. Esta implementación  obtiene un costo de búsqueda de $O(\log_2 n)$ [@sadit_algoritmos, sección 5.1.1].

Este algoritmo fue implementado en `Julia` mediante la función `busqueda_binaria()`, en la que se adicionó un argumento opcional para contabilizar el número de veces que se calcula el punto medio, que corresponde al costo del problema.

```{julia}
function busqueda_binaria(
    A::Vector{T}, 
    x::T, 
    c::Union{Nothing, Int64} = nothing,
    inicio::Int64 = 1, 
    final::Int64 = length(A) ) where {T}
    while inicio < final
        medio = (inicio + final) ÷ 2
        if x <= A[medio]
            final = medio
        else
            inicio = medio + 1
        end
        
        if c isa Int64
            c += 1
        end
    end
    p = x <= A[inicio] ? inicio : inicio + 1
    return p, c
end
```

```{julia}
#| include: false
# Funciona bien :)
for x in [0, 69, 70, 71]
    println( busqueda_binaria([10, 20, 30, 40, 50, 60, 70], x) )
    println( busqueda_binaria([10, 20, 30, 40, 50, 60, 70], x, 0) )
end
```

De acuerdo con @sadit_algoritmos[sección 5.2], cuando $n \to \infty$ o la relación $\frac{p}{n} \to 0$, es más útil definir un rango que pueda contener la respuesta antes de aplicar la búsqueda binaria. Esto se puede implementar mediante una familia de algoritmos $B_k$, cuyos primeros miembros se explican e implementan en las siguientes subsecciones. También se explica un algoritmo basado en la estructura SkipLists que tiene esta misma inspiración.

Con base en esta observación, el único algoritmo de búsqueda que depende del tamaño del arreglo, $n$, que se analiza en este documento es el implementado mediante `busqueda_binaria()`. En las siguientes subsecciones, se presentan algoritmos adaptativos que dependen de $p$.

## Búsqueda secuencial $B_0$

Sea $F_0(n) = 1, 2, \dots, n, n + 1$ una secuencia de puntos en los que se harán comparaciones entre $x$ y $a_{F_0(n)}$. Es decir, este algoritmo implementa una búsqueda exhaustiva al comparar $x$ con cada valor del arreglo $A$, por lo que no requiere una búsqueda binaria y su costo de búsqueda corresponde a todas las comparaciones que se deben hacer hasta llegar a la posición de inserción $C_0(p) = p + 1$ [@sadit_algoritmos, sección 5.2.1].

Para implementar el algoritmo, se debe iniciar la búsqueda en el primer elemento de A y continuarla hasta que se encuentre el elemento de $A$ que sea mayor que $x$ o se recorra todo el arreglo, entonces la posición de inserción de $x$ será la posición de dicho elemento [@sadit_algoritmos, sección 5.1.1].

Este algoritmo se implementó en `Julia` mediante la función `busqueda_b0()`, en la que se adicionó un argumento opcional para contabilizar el número de veces que se realizan comparaciones, que corresponde al costo del problema.

```{julia}
function busqueda_b0(
    A::Vector{T},
    x::T,
    c::Union{Nothing, Int64} = nothing) where {T}
    punto = 1
    n = length(A)
    while punto <= n && x > A[punto]
        punto += 1
        if c isa Int64
            c += 1
        end
    end
    return (punto, c)
end
```

```{julia}
#| include: false
# Funciona bien :)
# Preguntar si el costo es p - 1
for x in [0, 69, 70, 71]
    println( busqueda_b0([10, 20, 30, 40, 50, 60, 70], x) )
    println( busqueda_b0([10, 20, 30, 40, 50, 60, 70], x, 0) )
end
```

## Búsqueda secuencial $B_1$

Sea $F_1(n) = 2^1, 2^2, \dots, 2^{\log_2 \lfloor n \rfloor + 1}$ una secuencia de puntos en los que se harán comparaciones entre $x$ y $a_{F_1(n)}$, que servirán para determinar el rango en el que se realizará la búsqueda binaria $A[2^{\lfloor \log_2 p \rfloor + 1}:2^{\lfloor \log_2 (p + 1) \rfloor + 1}]$; entonces, dependiendo de la posición $p$, el número de comparaciones que se deben realizar para determinar este rango está determinado por $\lfloor \log_2 p + 1 \rfloor + 1$. Una vez determinado, el número de comparaciones que se realizan en dicho rango está determinado por $O(\log_2 n^\prime)$ donde $n^\prime$ es el tamaño del arreglo en el que se realiza la búsqueda binaria. Por lo tanto, el costo total de la búsqueda implementada es $C_1(p) < 2 \log_2 p + O(1)$ [@sadit_algoritmos, sección 5.2.2].

Este algoritmo se implementó en `Julia` mediante la función `busqueda_b1()`, en la que se adicionó un argumento opcional para contabilizar el número de veces que se realizan comparaciones, que corresponde al costo del problema.

```{julia}
function busqueda_b1(
    A::Vector{T}, 
    x::T,
    c::Union{Nothing, Int64} = nothing) where {T}
    n = length(A)
    p = 0

    # Determinar el rango
    # Duplicar la posición de búsqueda e ir actualizando la posición de inicio
    iteracion = 1
    while iteracion + 1 <= n && A[iteracion + 1] < x
        p = iteracion
        iteracion *= 2

        if c isa Int64
            c += 1
        end
    end

    # Realizar la búsqueda dentro del rango
    p, c = busqueda_binaria(A, x, c, p + 1, min(n, iteracion + 1))
    
    return p, c
end
```

```{julia}
#| include: false
# Funciona bien :)
# Preguntar si el costo es p - 1
for x in [0, 69, 70, 71]
    println( busqueda_b1([10, 20, 30, 40, 50, 60, 70], x) )
    println( busqueda_b1([10, 20, 30, 40, 50, 60, 70], x, 0) )
end
```

## Búsqueda secuencial $B_2$

Sea $F_2(n) = 2^{2^1}, 2^{2^2}, \dots, 2^{2^{\lfloor \log_2 \lfloor \log_2 (p + 1) + 1 \rfloor + 1}}$ una secuencia de puntos en los que se harán comparaciones entre $x$ y $a_{F_2(n)}$, que servirán para determinar el rango en el que se realizará la búsqueda binaria $A[2^{2 \lfloor \log_2 \lfloor \log_2 p \rfloor + 1 \rfloor + 1}:2^{2 \lfloor \log_2 \lfloor \log_2 (p + 1) \rfloor + 1 \rfloor + 1}]$; entonces, dependiendo de la posición $p$, el número de comparaciones que se deben realizar para determinar este rango está determinado por $\lfloor \log_2 \lfloor \log_2 (p + 1) \rfloor + 1 \rfloor + 1$. Una vez determinado este rango, se puede aplicar la búsqueda $B_1$ sobre él. Por lo tanto, el costo total de la búsqueda implementada es $C_2(p) < \log_2 p + 2 \log_2 \log_2 p + O(1)$ [@sadit_algoritmos, sección 5.2.2].

Este algoritmo se implementó en `Julia` mediante la función `busqueda_b2()`, en la que se adicionó un argumento opcional para contabilizar el número de veces que se realizan comparaciones, que corresponde al costo del problema.

```{julia}
function busqueda_b2(
    A::Vector{T}, 
    x::T,
    c::Union{Nothing, Int64} = nothing ) where {T}
    n = length(A)
    p1 = 0

    # Determinar el rango
    # Duplicar la posición de búsqueda e ir actualizando la posición de inicio
    iteracion = 1
    valor = 2^(2^iteracion)
    while valor + 1 <= n && A[valor + 1] < x
        p1 = valor
        iteracion += 1
        valor = 2^(2^iteracion)

        if c isa Int64
            c += 1
        end
    end

    # Realizar la búsqueda dentro del rango
    p, c = busqueda_b1(A[(p1 + 1):min(valor, n)], x, c)
    
    return p + p1, c
end
```

```{julia}
#| include: false
# Funciona bien :)
# Preguntar si el costo es p - 1
for x in [0, 69, 70, 71]
    println( busqueda_b2([10, 20, 30, 40, 50, 60, 70], x) )
    println( busqueda_b2([10, 20, 30, 40, 50, 60, 70], x, 0) )
end
```

## Busqueda mediante SkipLists

Como se explicó en el documento "*Algoritmos de Ordenamiento. 3.A. Experimentos y análisis*", se puede implementar una "*SkipList*" en `Julia` mediante las estructuras mutables `Nodo` y `Lista_Salto`, como se muestra a continuación.

```{julia}
# Nodos
mutable struct Nodo{T}
    valor::T
    sucesores::Vector{ Union{Nodo{T}, Nothing} }
end

Nodo{T}(valor::T, nivel::Int64) where {T} = Nodo{T}(
    valor, 
    Vector{ Union{Nodo{T}, Nothing} }(nothing, nivel) )
Nodo(valor::T, nivel::Int64) where {T} = Nodo{T}(valor::T, nivel::Int64)

# Listas
mutable struct Lista_Salto{T}
    nivel_maximo::Int64
    cabeceras::Vector{ Union{Nodo{T}, Nothing} }
end

Lista_Salto{T}() where {T} = Lista_Salto(
    1, 
    Vector{ Union{Nodo{T}, Nothing}}(nothing, 1) )
Lista_Salto() = Lista_Salto{T}() where {T}
```

En dicho documento, se formuló una función `inserta_skiplist!()` que recibe una lista y un valor como argumentos y cuyo resultado es la misma lista modificada al incluir el valor como uno de sus nodos. La construcción del nodo tiene un componente aleatorio que determina el número de punteros que tiene hacia otros nodos que contienen valores superiores al insertado. Para permitir la reproducibilidad de los resultados obtenidos, se adicionó un argumento opcional, `rng`, que permite indicar un generador de números aleatorio mediante el cual se determina dicho tamaño del nodo; este argumento no estaba disponible en el documento señalado.

```{julia}
function inserta_skiplist!(
    lista::Lista_Salto{T}, 
    valor::T, 
    c::Union{ Int64, Nothing } = nothing,
    rng = nothing) where {T}
    # Asignar aleatoriamente un nivel
    nivel = 1
    if rng isa Nothing
        while rand() <= 0.5
            nivel += 1
        end
    else
        while rand(rng) <= 0.5
            nivel += 1
        end
    end

    # Si la lista tiene menos niveles, adicionar los restantes a
    # la cabecera
    if nivel > lista.nivel_maximo
        for k in (lista.nivel_maximo + 1):nivel
            push!(lista.cabeceras, nothing)
        end
        lista.nivel_maximo = nivel
    end

    # Nuevo nodo
    y = Nodo{T}(valor, nivel)
    
    # Actualizar los punteros desde el máximo nivel que estoy insertando
    for k in nivel:-1:1
        # Contabilizar el número de actualizaciones del puntero
        if !(c isa Nothing)
            c += 1            
        end

        x = lista.cabeceras[k]
        if x isa Nothing
            # Si el nivel k de la cabecera está vacío, entonces apunta
            # al nuevo nodo
            lista.cabeceras[k] = y
        elseif valor < x.valor
            # Si lo que se inserta es pequeño, entonces se actualiza desde
            # el principio
            lista.cabeceras[k] = y
            y.sucesores[k] = x
        else
            # Si no está vacío, buscamos hasta que el nivel de algún 
            # sucesor sea menor y quebramos los apuntadores
            z = x.sucesores[k]
            while !(z isa Nothing) && (valor > z.valor)
                x = z
                z = z.sucesores[k]
            end
            x.sucesores[k] = y
            y.sucesores[k] = z
        end
    end
    return c
end
```

```{julia}
#| include: false

x = Lista_Salto{Int64}()
for numero in 1:10
    inserta_skiplist!(x, rand(rng, 1:10), nothing, rng)
end
x
```

En ese mismo documento se había señalado que para organizar un arreglo mediante una SkipList bastaba insertar cada elemento del arreglo en una lista nueva y, una vez generada, seguir los apuntadores en el nivel $k = 1$ desde la cabecera de la lista hasta encontrar el valor que indica el final. Este algoritmo se había implementado en `Julia` mediante la función `ordenar_skiplist()`, que se reproduce a continuación, con los siguientes cambios:

+ Se adiciona un tercer valor entregado por la función, correspondiente a la SkipList generada a partir del arreglo original, y
+ El arreglo ordenado tiene el tipo que corresponde al tipo de los elementos del arreglo original.

```{julia}
function ordenar_skiplist(
    a::Vector, 
    c::Union{ Int64, Nothing } = nothing, 
    rng = nothing)
    listado = Lista_Salto{eltype(a)}()
    ordenar = Vector{eltype(a)}()
    for elemento in a
        c = inserta_skiplist!(listado, elemento, c, rng)
    end
    siguiente = listado.cabeceras[1]
    while !(siguiente isa Nothing)
        push!(ordenar, siguiente.valor)
        siguiente = siguiente.sucesores[1]
    end
    return (c, ordenar, listado)
end
```

```{julia}
#| include: false

# Parece que funciona bien para ordenar :)
println( ordenar_skiplist(rand(1:100, 10), nothing, rng) )
println( ordenar_skiplist(rand(1:100, 10), 0, rng) )
```

En adición a los elementos señalados, que ya habían sido trabajados en el documento "*Algoritmos de Ordenamiento. 3.A. Experimentos y análisis*", se generó la función `busqueda_skiplist()`, que implementa un algoritmo adaptativo para buscar un valor $x$ en una SkipList. A diferencia de los algoritmos señalados en las subsecciones anteriores, este no entrega la posición en la cual se debe insertar el valor para conservar el orden del arreglo, pues ello no tiene sentido para una SkipList, sino que entrega la referencia del nodo que sería antecesor al nodo que se construya a partir del valor correspondiente, de forma que los apuntadores después de insertar este último mantengan el ordenamiento de la lista. El procedimiento implementado se describe a continuación:

+ Se busca el valor al que apuntan las cabeceras de la lista en las posiciones $F(n) = 2^0, 2^1, \dots, 2^{\lfloor \log_2 n + 1 \rfloor}$.
+ Se identifica el nodo con el valor más grande en dicha lista, cuyo valor es inferior al valor buscado $x$. Es decir, se reduce la dimensionalidad del rango buscado al eliminar los primeros nodos más pequeños que el valor buscado.
+ Se realiza una búsqueda descendiendo de nivel, del nodo más grande en la lista que es inferior al valor buscado.

Se adicionó un parámetro opcional en esta función que contabiliza el número de comparaciones que realiza el algoritmo, que es proporcional a su costo de ejecución. Debido al primer inciso señalado, se espera que este costo sea proporcional al valor de $p$, no al tamaño completo de la SkipList.

```{julia}
function busqueda_skiplist(
    lista::Lista_Salto{T}, 
    valor::T, 
    c::Union{ Int64, Nothing } = nothing ) where {T}
    k = 1
    while k <= lista.nivel_maximo && lista.cabeceras[k].valor < valor
        k *= 2

        if c isa Int64
            c += 1
        end
    end
    k = min(k, lista.nivel_maximo)

    if lista.cabeceras[k].valor >= valor
        inferior = lista.cabeceras
    else
        inferior = lista.cabeceras[k]
        while k >= 1
            # Contabilizar el número de actualizaciones del puntero
            if !(c isa Nothing)
                c += 1            
            end
            
            siguiente = inferior.sucesores[k]
            if siguiente isa Nothing || siguiente.valor >= valor
                k -= 1
            else
                # Si no está vacío, buscamos hasta que el nivel de algún 
                # sucesor sea menor y quebramos los apuntadores
                inferior = siguiente
            end
        end
    end
    return inferior, c
end
```

```{julia}
#| include: false
# Funciona bien :)

_, _, lista = ordenar_skiplist([10, 20, 30, 40, 50, 60, 70], nothing, rng)
for x in [0, 69, 70, 71]
    println( busqueda_skiplist( lista, x ) )
    println( busqueda_skiplist( lista, x, 0) )
end
```

# Experimentos {#sec-experimentos}

Como fue señalado en la sección anterior, se espera que el costo de ejecución de `busqueda_binaria()` sea proporcional al tamaño del arreglo, mientras que el de las demás funciones debería ser proporcional a $p$. En este sentido, en esta sección se realizan experimentos con diversos valores de $p$ para verificar si se satisface esta expectativa teórica en las funciones implementadas. En la @sec-datos se describen los datos utilizados y las consultas que fueron realizadas sobre ellos. En la @sec-tiempo, se analizan los tiempos de ejecución y en la @sec-cuenta se contabiliza el número de operaciones. En ambos casos, se observa que se los resultados obtenidos no fueron los esperados.

## Datos {#sec-datos}

Se obtuvieron diccionarios de arreglos desordenados disponibles en 6 archivos electrónicos en formato de Notación de Objetos de JavaScript (JSON, por sus siglas en inglés). Cada uno de estos diccionarios se incorporó como un diccionario interior de otro denominado `datos`, cuyas claves corresponden a un número asociado a cada archivo electrónico con la información original.

```{julia}
datos = Dict()
for numero in ["016", "032", "064", "128", "256", "512"]
    datos[parse(Int64, numero)] = JSON.parsefile(
        "4_1_Datos_Reporte3A/listas-posteo-con-perturbaciones-p=$(numero).json"
        )
end
```

Como las fucniones `busqueda_binaria()`, `busqueda_b0()`, `busqueda_b1()` y `busqueda_b2()` requieren como entrada un arreglo ordenado y la función `busqueda_skiplist()` requiere una SkipList, entonces se procesaron los arreglos desordenados originalmente disponibles en cada diccionario interior para convertirlos en uno de estos dos tipos de insumo. Para ello, cada uno de los arreglos originales se procesó mediante la función `ordenar_skiplist()` y se conservaron las respuestas del arreglo ordenado y la SkipList que se obtienen a partir de esta función; estos arreglos se registraron en un diccionario ubicado en el lugar de memoria en que estaba originalmente disponible el insumo para esta función, que también se conservó en el mismo diccionario.

```{julia}
for numero in keys(datos)
    for asunto in keys(datos[numero])
        _, ordenado, skiplist = ordenar_skiplist( datos[numero][asunto] )
        datos[numero][asunto] = Dict(
            "original" => datos[numero][asunto], 
            "ordenado" => ordenado, 
            "skiplist" => skiplist 
            )
    end
end
```

Asimismo, se obtuvieron números para consultar en los diferentes arreglos a partir de 4 archivos electrónicos en formato JSON. Estos se registraron en un diccionario denominado `consultas`, cuyas claves son asociadas al archivo electrónico correspondiente y cuyos valores son los arreglos con los números de consulta que se realizarán.

```{julia}
consultas = Dict()
for numero in [1, 2, 3, 4]
    consultas[numero] = JSON.parsefile(
        "5_1_Consultas_Reporte4A/consultas-$(numero)-listas-posteo.json"
    )
end
```

## Tiempo de ejecución {#sec-tiempo}

Para cada una de las claves de `consultas` y cada uno de los valores de los vectores asociados a dichas claves, se realizaron 5 experimentos, uno para cada una de las funciones analizadas. Cada experimento consistió en recorrer 100 veces todos los arreglos disponibles en `datos` y ejecutar la función respectiva al experimento con el número buscado; de cada experimento se registró el tiempo promedio para la ejecución de las 100 iteraciones de cada función sobre todos los arreglos, así como información descriptiva sobre el mismo experimento (el nombre de la función, el archivo de consulta y el número buscado). Esta información se registró en un `DataFrame` denominado `labbusc`.

```{julia}
experimentos = ["busqueda_binaria", "busqueda_b0", "busqueda_b1", 
                "busqueda_b2", "busqueda_skiplist"]
labbusc = DataFrame(
    Funcion = Vector{String}(), 
    Archivo_Consulta = Vector{Int64}(), 
    Valor_Consulta = Vector{Int64}(), 
    Tiempo_Total = Vector{Float64}()
    )
    
# Vamos a guardar el número de la consulta, el experimento y cuánto se demora realizándola, 
# independientemente de la lista de posteo (ya da igual porque están organizados)
for num_consulta in 1:4
    for consulta in consultas[num_consulta]
        for experimento in experimentos
            # Midamos el tiempo que se demora cada función en buscar cada 
            # consulta en todos los vectores de las listas de posteo
            f = Symbol(experimento)
            f = getfield(Main, f)
            x = now()
            for i in 1:100
                for num_lista in keys(datos)
                    for asunto in keys(datos[num_lista])
                        if experimento != "busqueda_skiplist"
                                f(datos[num_lista][asunto]["ordenado"], num_consulta)
                        else
                                f(datos[num_lista][asunto]["skiplist"], num_consulta)
                        end
                    end
                end
            end
            push!(labbusc, 
                  (experimento, num_consulta, consulta, Dates.value( now() - x ) / 100) )
        end
    end
end
```

En la @tbl-labbusc se muestran los resultados de los primeros 20 experimentos obtenidos mediante este procedimiento.

```{julia}
#| label: tbl-labbusc
#| tbl-cap: "Resultado de los primeros 20 experimentos en `labsuc`"

first(labbusc, 20) |> markdown_table()
```

Asimismo, en la @fig-labbusc se muestra el tiempo promedio (eje vertical) obtenido de la ejecución de cada función, como una función del valor buscado (eje horizontal). En esta figura no se observa que a mayor valor buscado aumente el tiempo de ejecución, sino que se ve un tiempo de ejecución relativamente homogéneo. Es decir, no se observa el resultado esperado según los elementos descritos en la @sec-busqueda.

```{julia}
#| label: fig-labbusc
#| fig-cap: "Tiempo promedio por experimento"

@df labbusc plot(:Valor_Consulta, :Tiempo_Total, group = :Funcion, seriestype = :scatter)
```

## Contabilización del número de comparaciones {#sec-cuenta}

Homólogamente, se contabilizó el número de comparaciones que requirió cada algoritmo para realizar la búsqueda de cada valor de los vectores disponibles en `consulta`, en todos los arreglos disponibles en `datos`. A diferencia del caso anterior, este experimento se realizó una única vez por experimento, pues el número de comparaciones es determinístico.

```{julia}
labcont = DataFrame(
    Funcion = Vector{String}(), 
    Archivo_Consulta = Vector{Int64}(), 
    Valor_Consulta = Vector{Int64}(), 
    Cuenta_Total = Vector{Int64}()
    )
    
for num_consulta in 1:4
    for consulta in consultas[num_consulta]
        for experimento in experimentos
            f = Symbol(experimento)
            f = getfield(Main, f)
            c = 0
            for num_lista in keys(datos)
                for asunto in keys(datos[num_lista])
                    if experimento != "busqueda_skiplist"
                            _, c0 = f(datos[num_lista][asunto]["ordenado"], num_consulta, 0)
                    else
                            _, c0 = f(datos[num_lista][asunto]["skiplist"], num_consulta, 0)
                    end
                    c += c0
                end
            end
            push!(labcont, 
                  (experimento, num_consulta, consulta, c) )
        end
    end
end
```

En la @tbl-labcont se muestran los resultados de los primeros 20 experimentos obtenidos mediante este procedimiento.

```{julia}
#| label: tbl-labcont
#| tbl-cap: "Resultado de los primeros 20 experimentos en `labsuc`"

first(labcont, 20) |> markdown_table()
```

En la @fig-labcont se muestra el número de comparaciones realizadas por valor buscado. De forma homóloga al caso anterior, se observa que estas no dependen del valor, en contraposición a la expectativa. Sin embargo, se observa que la búsqueda binaria ofrece un desempeño ineficiente, pues tiene un número de comparaciones superior a las demás funciones.

```{julia}
#| label: fig-labcont
#| tbl-cap: "Número de comparaciones por experimento"

@df labcont plot(:Valor_Consulta, :Cuenta_Total, group = :Funcion, seriestype = :scatter)
```

# Conclusión {#sec-conclusion}

Se esperaba que los algoritmos implementados tuvieran un desempeño proporcional al logaritmo del valor buscado, por lo que tenían un desempeño óptimo. Sin embargo, los resultados obtenidos arrojaron un desempeño plano con respecto al valor buscado, situación que es marcadamente diferente a la esperada. Es necesario una mayor profundización en el estudio de los algoritmos para determinar la causa de este comportamiento, que puede deberse a una mala implementación de las funciones en `Julia` debida a un incorrecto entendimiento de los algoritmos teóricos, o a algún otro problema que aún no se comprende de forma completa.

# Referencia